### ISSUE TITLE
Log file unreadable

### ISSUE THREAD

**Issue by quixoft** [CosmicPi/cosmicpi-daq#12]
Please put some carriage returns and maybe a blank line to separate the entries in the log file.

**Comment by juzsal** [comment]
Good, thanks for reporting. Glad we are starting to do this properly. I will push a fix for this in a few minutes.

I hadn't really been using the logging option since the beginning, since there were a couple of issues with it (log rotation, file naming, flushing, etc.) that will get sorted out when we put in place a more robust logging implementation.

**Comment by quixoft** [comment]
Yes it's starting to look good, the daq has Benn running flawlessly all afternoon, so congratulations are in order
